### ISSUE TITLE
lavuk key

### ISSUE THREAD

**Issue by ahmeteme** [ioskanadase/neoeday#1]
Başlık:
🛠 Login butonu çalışmıyor

Açıklama:

Problem: Ana sayfadaki “Login” butonuna tıkladığımda hiçbir şey olmuyor.
Beklenen Davranış: Login butonuna tıkladığımda kullanıcı giriş formunun açılması gerekiyor.
Adımlar:
Ana sayfaya git
Login butonuna tıkla
Beklenen davranış yerine butonun tepkisiz kalması gözlemleniyor.

**Comment by zkInvisible** [comment]
eyw karşim halledıcez
